

- name: Create directories per tenant for storing the declarations
  file: 
    path: "..files/t_{{APPLICATION_NAME}}"
    state: directory
  tags:
    - create-app
    - tcp


- name: Build JSON payload using template for one app folder
  template: 
    src: "tcp.j2" 
    dest: "..files/t_{{APPLICATION_NAME}}/{{APPLICATION_NAME}}_as3.json"
  tags:
    - create-app
    - tcp


- name: Deploy an tcp app service configuration
  bigip_appsvcs_extension:
    content: "{{ lookup('file', '../files/t_{{APPLICATION_NAME}}/{{APPLICATION_NAME}}_as3.json') }}"
    state: present
    provider: 
      password: "{{ password }}"
      server: "{{ server }}"
      user: "{{ user }}"
      server_port: "{{ server_port }}"
      validate_certs: no
  delegate_to: localhost
  tags:
    - create-app
    - tcp