- name: COLLECT BIG-IP Devices
  bigip_device_info:
    provider: 
      server: "{{ inventory_hostname }}"
      user: "{{ user }}"
      password: "{{ password }}"
      server_port: "{{ server_port }}"
      validate_certs: no
    gather_subset:
      - "{{ fact }}"
  delegate_to: localhost
  tags:
    - device-info
    - devices