
---

  - name: Create temporary directories for storing variables 
    file: 
      path: "{{ role_path }}/tmp/{{ group_names[0] }}/{{ inventory_hostname_short }}"
      state: directory

  - name: Download environment details from intent data
    get_url:
      url: "https://raw.githubusercontent.com/arunhotra/base-repo/master/{{ group_names[0] }}/envDefaultBuildvalues.json"
      dest: "{{ role_path }}/tmp/{{ group_names[0] }}/{{ inventory_hostname_short }}/common_deviceVars.json"

  
  - name: Download device details from intent data for devices
    get_url:
      url: "https://raw.githubusercontent.com/arunhotra/base-repo/master/{{ group_names[0] }}/{{ inventory_hostname_short }}.json"
      dest: "{{ role_path }}/tmp/{{ group_names[0] }}/{{ inventory_hostname_short }}/base_deviceVars.json"


  - name: Creating device variables from sourcedepot
    include_vars:
      name: "device_vars"
      dir: "{{ role_path }}/tmp/{{ group_names[0] }}/{{ inventory_hostname_short }}/"
      files_matching: _deviceVars.json

  - name: Print device_vars
    debug:
      msg: "{{device_vars}}"
