---


  - name: Print rendered DO declaration
    debug:
      msg: "{\"DO_declaration\": {{ lookup('template','{{ role_path }}/templates/template_DO_declaration_BIG-IP.j2') }}}"
    with_dict: "{{device_vars}}"


  - name: "REST call DO declaration to BIG-IPs"
    uri:
      url: "https://{{inventory_hostname}}:{{bigip_port}}/mgmt/shared/declarative-onboarding"
      method: POST
      body: "{{ lookup('template','{{ role_path }}/templates/template_DO_declaration_BIG-IP.j2') }}"
      headers:
        Content-Type: "application/json"
      return_content: yes
      body_format: json
      status_code: 202
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    register: DO_output
    with_dict: "{{device_vars}}"



  - name: Creating DO task variable for subsequent tasks 
    set_fact:
      id: "{{DO_output.results[0].json.id}}"



  - name: Delay checking BIG-IP for 30 seconds allowing DO declaration to process
    bigip_wait:
      timeout: 600
      delay: 30
      provider: "{{ provider }}"
    with_dict: "{{device_vars}}"


  - name: "REST to check for Successfull DO Declaration to both BIG-IPs"
    uri:
      url: "https://{{inventory_hostname}}:{{bigip_port}}/mgmt/shared/declarative-onboarding/task/{{id}}"
      method: GET
      return_content: yes
      status_code: [200, 202]
      url_username: "{{bigip_username}}"
      url_password: "{{bigip_password}}"
      force_basic_auth: yes
      validate_certs: no
    register: DO_task_check
    until: DO_task_check.json.result.message.find("success") != -1
    retries: 40
    delay: 15
