---
  
  - name: Setup provider
    set_fact:
      provider:
        server: "{{inventory_hostname}}"
        user: "{{bigip_username}}"
        password: "{{bigip_password}}"
        server_port: "{{bigip_port}}"
        validate_certs: "{{validate_certs}}"